// Prints the 1Password SSO test vectors, computed by the C# password-manager-access library.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using PasswordManagerAccess.Common;
using PasswordManagerAccess.OnePassword;
using Ristretto;

static byte[] Seq(int n, int start = 0) => Enumerable.Range(start, n).Select(i => (byte)i).ToArray();
static string B64(byte[] b) => b.ToUrlSafeBase64NoPadding();
static string Hex(byte[] b) => Convert.ToHexString(b).ToLowerInvariant();

var username = "user@example.com";
var signInAddress = "https://acme.1password.com";
var enrollmentUuid = "k5x2ooeirvhpxq6s4mdkfexbiu";
var verificationCode = "ABCD-1234";
var salt = Seq(16, 1);
var sessionId = Seq(16, 100);
var clientSecret = Seq(64);
var yaSecret = Seq(64, 64);

// The CPace generator point does not depend on ya, so ya is built from it the way the enrolled device does.
var passcodeHash = Client.CalculatePasscodeHash(verificationCode, salt);
var adOnly = new Client.MsgA([], new Client.Ad(1, salt, sessionId), []);
var firstHash = Client.CalculateFirstHash(username, signInAddress, enrollmentUuid, adOnly);
var secondHash = Client.CalculateSecondHash(firstHash, passcodeHash, adOnly);
var generator = RistrettoElement.FromUniformBytes(secondHash);
var yaScalar = Scalar.FromBytesModOrderWide(yaSecret);
var ya = generator.Multiply(yaScalar).Compress().ToByteArray();

var msgAJson = JsonSerializer.SerializeToUtf8Bytes(
    new Dictionary<string, object>
    {
        ["ya"] = B64(ya),
        ["ad"] = new Dictionary<string, object>
        {
            ["version"] = 1,
            ["salt"] = B64(salt),
            ["session_id"] = sessionId.Select(x => (int)x).ToArray(),
        },
    }
);
var msgA = Client.ParseMsgA(msgAJson);

var msgB = Client.CalculateMsgB(username, signInAddress, enrollmentUuid, verificationCode, msgA, clientSecret);
var authA = Client.CalculateAuthAHash(msgA, clientSecret);
var authB = Client.CalculateAuthBHash(authA, msgA, msgB);
var tagB = Client.CalculateTagB(authB, msgB);
var exchangeKey = Client.DeriveExchangeKey(authB);

// The enrolled device's view: the same shared point from the other side.
var serverShared = new CompressedRistretto(msgB).Decompress().Multiply(yaScalar).Compress().ToByteArray();
if (!serverShared.SequenceEqual(authA))
    throw new Exception("CPace sides disagree");

var bundleJson = """{"srpx":"oKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr8","auk":{"alg":"A256GCM","k":"WyICHHlP5lPigZUGZYoivbJMqgHjSti86UKwdjCryYM","kty":"oct","kid":"mp"}}""";
var bundleBytes = Encoding.UTF8.GetBytes(bundleJson);
var enrollIv = Seq(12, 200);
var transportKey = new AesKey("1P_SSO_ENROLLMENT_TRANSPORT_KEY", exchangeKey);
var encryptedEnroll = transportKey.Encrypt(bundleBytes, enrollIv, "1P_SSO_CREDENTIAL_BUNDLE:ENROLL"u8.ToArray()).ToModel();
var decryptedEnroll = Client.DecryptCredentials(encryptedEnroll, exchangeKey);
if (decryptedEnroll.SrpX != "oKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr8")
    throw new Exception("enroll round trip failed");

// Local storage
var derivation = new Client.DeviceKeyDerivation("m3h6kz4qjbj5xlzp7g2vy3tq4e", Seq(32, 10), Seq(48, 50));
var deviceKey = Client.DeriveDeviceKey(derivation);
var storageIv = Seq(12, 30);
var storedDerivation = Client.EncryptForStorage(derivation, storageIv).ToModel();
var roundTrip = Client.DecryptDeviceKey(storedDerivation);
if (!roundTrip.Key.SequenceEqual(derivation.Key))
    throw new Exception("storage round trip failed");

var localIv = Seq(12, 40);
var serializedBundle = JsonSerializer.SerializeToUtf8Bytes(Client.DecryptCredentials(encryptedEnroll, exchangeKey));
var encryptedLocal = deviceKey.Encrypt(serializedBundle, localIv, "1P_SSO_CREDENTIAL_BUNDLE:LOCAL2"u8.ToArray()).ToModel();
var restored = Client.DecryptCredentialBundle(encryptedLocal, deviceKey);
if (restored.Auk.KeyId != "mp")
    throw new Exception("local round trip failed");

var leb = new Dictionary<string, string>();
foreach (var len in new[] { 0, 1, 127, 128, 300, 16383, 16384 })
{
    using var memory = new MemoryStream();
    using var writer = new BinaryWriter(memory);
    Client.WriteLeb128Prefixed(writer, new byte[len]);
    writer.Flush();
    leb[len.ToString()] = Hex(memory.ToArray()[..^len]);
}

var redirectUrl =
    "https://acme.1password.com/sso/oidc/redirect/#code=1.ASgAwV5aTMWa%2Bkab&state=AheikL9HpINJRhPsoa9KWw&session_state=002f7c59-8098-a5c0-a0d5-dd5ed564dd9a";

var output = new Dictionary<string, object>
{
    ["_comment"] = "Generated by scripts/sso-vectors from the C# password-manager-access library. Binary values are lowercase hex unless noted.",
    ["cpace"] = new Dictionary<string, object>
    {
        ["username"] = username,
        ["sign_in_address"] = signInAddress,
        ["enrollment_uuid"] = enrollmentUuid,
        ["verification_code"] = verificationCode,
        ["client_secret"] = Hex(clientSecret),
        ["ya_secret"] = Hex(yaSecret),
        ["msga_json"] = Encoding.UTF8.GetString(msgAJson),
        ["passcode_hash"] = Hex(passcodeHash),
        ["first_hash"] = Hex(firstHash),
        ["second_hash"] = Hex(secondHash),
        ["msgb"] = Hex(msgB),
        ["auth_a"] = Hex(authA),
        ["auth_b"] = Hex(authB),
        ["tag_b"] = Hex(tagB),
        ["exchange_key"] = Hex(exchangeKey),
        ["credential_bundle_json"] = bundleJson,
        ["encrypted_credentials"] = encryptedEnroll,
    },
    ["local"] = new Dictionary<string, object>
    {
        ["device_key_id"] = derivation.Id,
        ["device_key_seed"] = Hex(derivation.Key),
        ["device_key_salt"] = Hex(derivation.Salt),
        ["device_key"] = Hex(deviceKey.Key),
        ["stored_device_key_derivation"] = storedDerivation,
        ["serialized_credential_bundle"] = Encoding.UTF8.GetString(serializedBundle),
        ["encrypted_credential_bundle"] = encryptedLocal,
        ["local_user_info_json"] = JsonSerializer.Serialize(
            new Dictionary<string, object>
            {
                ["userId"] = "USERUUID",
                ["accountId"] = "ACCOUNTUUID",
                ["credentialsEncryptionKeyId"] = derivation.Id,
                ["deviceKeyDerivation"] = storedDerivation,
            }
        ),
    },
    ["leb128_prefix"] = leb,
    ["redirect"] = new Dictionary<string, object>
    {
        ["url"] = redirectUrl,
        ["code"] = Url.ExtractAndDecodeQueryParameter(redirectUrl, "code")!,
        ["state"] = Url.ExtractAndDecodeQueryParameter(redirectUrl, "state")!,
    },
};

Console.WriteLine(JsonSerializer.Serialize(output, new JsonSerializerOptions { WriteIndented = true, Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping }));

